### ISSUE TITLE
Game Improvement proposal

### ISSUE THREAD

**Issue by tamet83** [lamarios/monopoly#5]
Hi,

by playing with my friends we noticed this things:

- Vine Street has worng rent price, there is an extra 1;
- Is it possible to keep in memory a longer log? Otherwise can you tell me where is kept the full log?
- Is it possible to implement a more automated money transition? Especially with the bank. I.E. if someone buy a deed from the bank, the bank shoud keep automatically the money from the player.
- Can you change the dollar player symbol? Is a bit misleading being the same of the bank.

Many thanks for you work, I really appreciate it.

**Comment by lamarios** [comment]
-  Vine Street has worng rent price, there is an extra 1;
This should be already fixed in the last version of the image

- Is it possible to keep in memory a longer log? Otherwise can you tell me where is kept the full log?
Yeah I can work on that

- Is it possible to implement a more automated money transition? Especially with the bank. I.E. if someone buy a deed from the bank, the bank shoud keep automatically the money from the player.

So this one I don't think I'll do it. When I originally did the game, I wanted close to zero automation to reproduce the board game experience and I'll most likely stick to it. When I played with friends their feed back was that it was surprisingly nice to have to do all this because it keeps player busy and engaged and everybody needs to pay attention (like the phyisical version), Also, I did this project as a one of and other than fixing bug and small QL improvement, I don't think I'll have the motivation to do changes that big  because everything is calculated based on bank notes, not overall balance. If I don't have exact change, the bank should send me back the change, what if somehow the bank doesn't have the notes to give me change ?


- Can you change the dollar player symbol? Is a bit misleading being the same of the bank.
That makes sense.

**Comment by tamet83** [comment]
Hello,

really thanks for your answers and your point of view about not automating the game have more sense than mine. Now I understand the motivations and I completely agree with you.

For the other answers, well, thank you so much.

Could you warn me when you'll finish the fixes?

**Comment by lamarios** [comment]
Ok done, the docker image is up to date. The logs are in a txt filed so it might require a refresh to get the updated as the browser might cache it.

**Comment by tamet83** [comment]
Hi again, I've deleted old container and pulled new one. The error on Vine Street is ok but I still can't see the new frog image.
Do I have to do something else?

Thank you

**Comment by lamarios** [comment]
In theory no. Can you see it in my demo instance. What about the logs ?

**Comment by tamet83** [comment]
Hi,
I confirm you that now seems work every thing. Many thanks again :)
